### ISSUE TITLE
Doesn't parse file with 2 bookmarks and one highlight

### ISSUE THREAD

**Issue by fancydev18** [DJTB/kindlequotes#1]
Hello! When parsing the attached file, there are no quotes returned.

Is there an issue with handling bookmarks?

Thanks
[My Clippings parse.txt](https://github.com/DJTB/kindlequotes/files/3062345/My.Clippings.parse.txt)

**Comment by fancydev18** [comment]
I made some progress. One fix was to change regexp to match "Location" too:

```
function parseLoc(str = "") {
    const [, loc] = safeMatch(str, /(?:location )(\d+-?\d+)/i)
```

Still, the content is parsed as empty.

**Comment by DJTB** [comment]
Hi @fancydev18, I never saw a notification for this issue, so sorry about that!

Taking a quick look at your clippings file, it seems to have a different format to what this code was setup to process: my Kindle PaperWhite (V6 I think...) 

Yours
```
- Your Bookmark on Page 118 | Location 1797 | Added on Sunday, February 10, 2019 8:29:24 AM
- Your Highlight on Page 12 | Location 170-172 | Added on Wednesday, April 3, 2019 8:40:13 PM
```

Mine
```
- Your Highlight at location 2030-2035 | Added on Monday, 15 August 2016 23:44:11
- Your Bookmark at location 2040 | Added on Tuesday, 16 August 2016 13:42:31
```

I can add a flag to process the alternative format, let me know if you'd still like to use this before I go ahead with that. 

Could you let me know which Kindle model (and/or firmware) you're using for reference? There may even be more versions of the Clippings file format out there.

**Comment by fancydev18** [comment]
Thanks Duncan,

My kindle paperwhite 2013, firmware 5.6.1
It would be nice to support parsing it as well, but if I just need to upgrade the firmware, that will do too.

**Comment by DJTB** [comment]
Probably best to just handle both formats anyway. I'll take a look at it this week 👍

**Comment by DJTB** [comment]
@fancydev18 Made a quick update to https://github.com/DJTB/kindlequotes/tree/alternate-format - do you want to try cloning that branch and parsing your clippings for me?

**Comment by fancydev18** [comment]
Thanks Duncan!
I'm no longer working on that project though :(
